services:
  langgraph_soa:
    build: 
      context: ./containers/langgraph_soa
      dockerfile: Dockerfile
    ports:
      - "8100:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./containers/langgraph_soa:/app
    networks:
      - rose_network

  container-orchestrator:
    build: 
      context: ./containers/container_orchestrator
    ports:
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rose_network

  dev_container:
    build:
      context: ./containers/dev_container
      dockerfile: Dockerfile
    ports:
      - "8010:8010"  # Terminal websocket
      - "8020:8020"  # File operations
      - "8030:4000"  # Command execution
      - "8040:8080"  # HTTP server
      - "3000:3000"  # Next.js dev server
    tty: true
    stdin_open: true
    volumes:
      - ./containers/dev_container:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    restart: unless-stopped
    networks:
      - rose_network

  ux:
    build:
      context: ./containers/ux_container
      dockerfile: Dockerfile
    ports:
      - "8090:8080"  # Map container port 8080 to host port 8090
    volumes:
      - ./containers/ux_container:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - rose_network

networks:
  rose_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
